### ISSUE TITLE
Cannot get Venv

### ISSUE THREAD

**Issue by Abraxos** [llllllllll/c-extension-tutorial#1]
Hello,

I tried to set this up, but I keep getting an error where the setup-env script never creates the venv:

```
...
renaming build/scripts-3.6/pydoc3 to build/scripts-3.6/pydoc3.6
renaming build/scripts-3.6/idle3 to build/scripts-3.6/idle3.6
renaming build/scripts-3.6/2to3 to build/scripts-3.6/2to3-3.6
renaming build/scripts-3.6/pyvenv to build/scripts-3.6/pyvenv-3.6
~/Desktop/c_extension_tutorial/c-extension-tutorial
bash: ./submodules/cpython/python: is a directory
cp: venv/bin/python-gdb.py: No such file or directory
bash: venv/bin/activate: No such file or directory
Requirement already satisfied: ipython in /usr/local/lib/python3.5/site-packages
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.5/site-packages (from ipython)
...
```

The issue is that there is a `./submodules/cpython/Python` directory (I am on MacOS X) and it seems like the `python` file was never compiled, although there is a `python.exe`.

Is there any idea as to how I might go about fixing this? I didn't want to rename the `Python` directory lest I break something else...

**Comment by llllllllll** [comment]
It looks like the default configure options for osx name the binary `python` because there is a directory called `Python` and the file system is case insensitive. I pushed a change that add `set -e` so the script will die on the first error and also detects osx and uses the name `python.exe` instead. I will test on osx later but if you want to try that would be great. Thanks!

**Comment by llllllllll** [comment]
I got an osx computer an tested the setup. It should work now.

**Comment by Abraxos** [comment]
OK I tried it myself and it seemed to work, but I have a couple of notes:

1) I think that when you added `set -e` there was an unintended side-effect, namely that when I follow the instructions in the readme and use `source` or `.` and there is an error the script actually exits the shell thus preventing the user from reading the error message. I got it to work by running bash inside of zsh and on error the script would exit from bash but leave me with the error message.

2) There was an issue with OpenSSL on Sierra that was causing me problems and I figure I should post the solution here for others. Basically, before running the scrip (assuming you have OpenSSL installed via Homebrew) you need to run these commands:

```
$ export CFLAGS="-I/usr/local/Cellar/openssl/1.0.2k/include"
$ export LDFLAGS="-L/usr/local/Cellar/openssl/1.0.2k/lib"
```

and only then would you be able to use the setup-env script effectively.

**Comment by Abraxos** [comment]
Concerning #1, it actually exits when the shell encounters *any* error, meaning that as soon as you have a compilation error in the venv/shell that it set up, it would boot you out of it.

**Comment by llllllllll** [comment]
Sorry about killing the terminal; I was worried that the `pip` commands would continue in the global env and mess stuff up but I forgot how that interacts with `source`. I moved the build steps into a subshell so it shouldn't kill the top level session.

re openssl: Do you have a non-standard openssl install? I have:

```bash
        CPPFLAGS="-I$(brew --prefix openssl)/include" \
                LDLAGS="-L$(brew --prefix openssl)/lib" \
                ./configure --with-pydebug
```

in the osx path, is `brew --prefix openssl` not `/usr/local/Cellar/openssl/1.0.2k/` on your system? I can manually include that path if it is a common location that is hard to deduce programatically.

I would like to thank you again for working through this. It will make install at the event much smoother!

**Comment by Abraxos** [comment]
Thanks for fixing the terminal issue!

re openssl: I am not totally sure how standard my openssl install is. `brew --prefix openssl` returns `/usr/local/opt/openssl`

re event: Sure! no problem. Glad I could help, and thank you for doing this.

**Comment by llllllllll** [comment]
What is the exact error you are getting with openssl, is `pip` failing? The `make` output will print something like: `Renaming _ssl because it failed to be imported` with an error message above it when it can't link against openssl. The error may give more insight into the problem.

If you cd into `submodules/cpython` and run `$ ./python.exe -c 'import _ssl'` what happens?

**Comment by Abraxos** [comment]
This is the error message that I get:

```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting ipython
  Could not fetch URL https://pypi.python.org/simple/ipython/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement ipython (from versions: )
No matching distribution found for ipython
```

**Comment by llllllllll** [comment]
Above that in the output of make there should be something like:

> The following packages were not installed:
>     _ssl ...

and then above that there should be an error about renaming _ssl because it couldn't be imported with some output from the linker.

Could you post that error message?

If it is just working when you explicitly pass those extra flags I could also just put them in the include / library path and be done with it.

**Comment by Abraxos** [comment]
It doesn't quite say it wasn't installed, but definitely related:

```
-L/usr/local/lib -o build/lib.macosx-10.11-x86_64-3.6-pydebug/_decimal.cpython-36dm-darwin.so
*** WARNING: renaming "_ssl" since importing it failed: dlopen(build/lib.macosx-10.11-x86_64-3.6-pydebug/_ssl.cpython-36dm-darwin.so, 2): Symbol not found: _CRYPTO_THREADID_set_callback
  Referenced from: build/lib.macosx-10.11-x86_64-3.6-pydebug/_ssl.cpython-36dm-darwin.so
  Expected in: flat namespace
 in build/lib.macosx-10.11-x86_64-3.6-pydebug/_ssl.cpython-36dm-darwin.so
*** WARNING: renaming "_hashlib" since importing it failed: dlopen(build/lib.macosx-10.11-x86_64-3.6-pydebug/_hashlib.cpython-36dm-darwin.so, 2): Symbol not found: _HMAC_CTX_copy
  Referenced from: build/lib.macosx-10.11-x86_64-3.6-pydebug/_hashlib.cpython-36dm-darwin.so
  Expected in: flat namespace
 in build/lib.macosx-10.11-x86_64-3.6-pydebug/_hashlib.cpython-36dm-darwin.so

Python build finished successfully!
The necessary bits to build these optional modules were not found:
ossaudiodev           spwd
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
atexit                pwd                   time

Following modules built successfully but were removed because they could not be imported:
_hashlib              _ssl
```

**Comment by llllllllll** [comment]
That is the same error I saw when I was using the system openssl. I wonder why your openssl is in a different location. For now I am going to add the directory you showed to the include/library path unless someone proposes a better solution.

**Comment by Abraxos** [comment]
Sure, but wouldn't this break it for people who do not have that weirdness with openssl?

**Comment by llllllllll** [comment]
Maybe? It looks like /usr/local/opt/openssl (brew --prefix openssl) is a symlink to the directory you mentioned. The mac I used was on 10.12.3, so it looks like it might be an issue with older versions of osx. I got that computer again and will try some stuff out.

**Comment by llllllllll** [comment]
I just misspelled LDFLAGS when I committed the change. Sorry about the trouble. I asked some people to run it and they could so hopefully it is working now.
